{
  "marketplace:installed:snippet:Fix-progress-bar-displacement": "{\"code\":\".main-connectBar-connectBar {\\n  overflow: visible !important;\\n  position: absolute !important;\\n  display: flex !important;\\n  align-items: unset !important;\\n  left: 80% !important;\\n  height: 20px !important;\\n  bottom: 1% !important;\\n  padding: 2px !important;\\n  background-color: transparent !important;\\n  color: var(--spice-text) !important;\\n}\\n.control-button::after {\\n  display: none !important;\\n}\",\"title\":\"Fix progress bar displacement\",\"description\":\"Fixes the progress bar displacement for a few themes. Better version of @CharlieS1103 Snippet\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/fix-progress-bar.png\"}",
  "marketplace:installed-extensions": "[\"marketplace:installed:ohitstom/spicetify-extensions/npvAmbience/npvAmbience.js\"]",
  "marketplace:installed:snippet:New-Hover-Panel": "{\"code\":\"#Desktop_LeftSidebar_Id {\\n  position: absolute;\\n  left: -280px;\\n  width: 288px;\\n  height: 100%;\\n  background-color: black;\\n  opacity: 0;\\n  visibility: visible;\\n  transition: left 0.5s ease, opacity 0.5s ease;\\n  z-index: 12;\\n}\\n#Desktop_LeftSidebar_Id:hover {\\n  left: 0;\\n  opacity: 1;\\n  visibility: visible;\\n}\\n:root {\\n  margin-left: -8px;\\n}\",\"title\":\"New Hover Panel\",\"description\":\"A New Hover Panel that servers the same purpose as the legacy 'Hover Panels', but only for the left sidebar and without modifying any other elements.\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/new-hover-panel.gif\"}",
  "marketplace:active-tab": "Installed",
  "marketplace:installed-themes": "[]",
  "marketplace:installed:snippet:Dark-Lyrics": "{\"code\":\".lyrics-lyrics-background { background-image: linear-gradient(315deg,var(--lyrics-color-background),black); background-size: 500%; } .lyrics-lyricsContent-lyric.lyrics-lyricsContent-highlight { color: white; } .lyrics-lyricsContent-lyric { color: #424242; }\",\"title\":\"Dark Lyrics\",\"description\":\"Replaces the highly saturated lyrics backgrounds with a very subtle dark gradient\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/dark-lyrics.png\"}",
  "marketplace:installed:ohitstom/spicetify-extensions/npvAmbience/npvAmbience.js": "{\"manifest\":{\"name\":\"NPV Ambience\",\"description\":\"Adds a colorful glow behind the Now Playing View image.\",\"preview\":\"npvAmbience/marketplace.png\",\"main\":\"npvAmbience/npvAmbience.js\",\"readme\":\"npvAmbience/README.md\",\"tags\":[\"interface\",\"decoration\"]},\"type\":\"extension\",\"title\":\"NPV Ambience\",\"subtitle\":\"Adds a colorful glow behind the Now Playing View image.\",\"authors\":[{\"name\":\"ohitstom\",\"url\":\"https://github.com/ohitstom\"}],\"user\":\"ohitstom\",\"repo\":\"spicetify-extensions\",\"branch\":\"main\",\"imageURL\":\"https://raw.githubusercontent.com/ohitstom/spicetify-extensions/main/npvAmbience/marketplace.png\",\"extensionURL\":\"https://raw.githubusercontent.com/ohitstom/spicetify-extensions/main/npvAmbience/npvAmbience.js\",\"readmeURL\":\"https://raw.githubusercontent.com/ohitstom/spicetify-extensions/main/npvAmbience/README.md\",\"stars\":110,\"lastUpdated\":\"2025-07-12T12:41:20Z\",\"created\":\"2023-05-12T00:35:27Z\"}",
  "marketplace:installed-snippets": "[\"marketplace:installed:snippet:New-Hover-Panel\",\"marketplace:installed:snippet:Fix-progress-bar-displacement\",\"marketplace:installed:snippet:Dark-Lyrics\",\"marketplace:installed:snippet:Thicker-Bars\",\"marketplace:installed:snippet:Fix-Listening-On\",\"marketplace:installed:snippet:Thin-Library-Sidebar-Rows\",\"marketplace:installed:snippet:Remove-connect-bar\"]",
  "marketplace:tabs": "[{\"name\":\"Extensions\",\"enabled\":true},{\"name\":\"Themes\",\"enabled\":true},{\"name\":\"Snippets\",\"enabled\":true},{\"name\":\"Apps\",\"enabled\":true},{\"name\":\"Installed\",\"enabled\":true}]",
  "marketplace:installed:snippet:Remove-connect-bar": "{\"code\":\".main-connectBar-connectBar {\\n  display: none !important;}\",\"title\":\"Remove connect bar\",\"description\":\"Remove connect bar that causes progress bar displacement when listening on different devices\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/remove-connect-bar.png\"}",
  "marketplace:local-theme": "marketplace",
  "marketplace:installed:snippet:Fix-Listening-On": "{\"code\":\".Svg-presentation-essentialBase-small-icon-autoMirror {fill: var(--spice-text);} .TypeElement-mesto-textBase-type {color: var(--spice-text) !important;} .main-devicePicker-indicator {display: none !important;} .main-nowPlayingBar-container {height: 72px !important;} .main-connectBar-connectBar {position: absolute !important; align-items: center !important; top: 42px !important; height: 32px !important; align-self: center !important; background-color: transparent !important; width: 30% !important;}\",\"title\":\"Fix Listening On\",\"description\":\"Fix listening on for some themes that move it up or make the text not visible\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/fix-listening-on.png\"}",
  "marketplace:installed:snippet:Thicker-Bars": "{\"code\":\".x-progressBar-progressBarBg { height: 100% !important; } .x-progressBar-sliderArea { height: 100% !important; } .x-progressBar-fillColor { height: 100% !important; }\",\"title\":\"Thicker Bars\",\"description\":\"Makes the song progress and volume bar thicker\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/thicker-bars.png\"}",
  "marketplace:installed:snippet:Thin-Library-Sidebar-Rows": "{\"code\":\".main-yourLibraryX-listItemGroup {grid-template-rows: none !important;} .main-yourLibraryX-listItemGroup * {padding-block: 0;}.main-yourLibraryX-listItem [role=\\\"group\\\"] {min-block-size: 0 !important;} .main-yourLibraryX-listItem .HeaderArea .Column {flex-direction: row; gap: 0.5em;} .main-yourLibraryX-listItem .HeaderArea * {padding-top: 0 !important; padding-bottom: 0 !important;} .main-yourLibraryX-listItem .x-entityImage-imageContainer, .main-yourLibraryX-rowCover {width: 1.6em !important; height: 1.6em !important;} .main-yourLibraryX-listRowSubtitle {padding-top: 0px;}\",\"title\":\"Thin Library Sidebar Rows\",\"description\":\"Single-line rows in the library sidebar, like the pre-2023 UI\",\"imageURL\":\"https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/assets/snippets/thin-library-sidebar-rows.png\"}"
}